### ISSUE TITLE
SSL cert for kindscript.com is invalid

### ISSUE THREAD

**Issue by sagevann** [Microsoft/kindscript#12]
Chrome is rejecting the SSL certificate issued for kindscript.com. The error is included below:

```
Your connection is not private

Attackers might be trying to steal your information from kindscript.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID
```

Macbook Air mid 2012
OS X Yosemite : 10.10.5
1.8GHz Core i5
8GB RAM
Version 48.0.2564.116 (64-bit)

**Comment by MaxPleaner** [comment]
seconding this. Also the website requires HTTP basic auth username and password. You are on the front page of Hacker News, so people are coming to the Github repo. Yet the link to the website (ostensibly where the docs are located) does not work.

**Comment by apopiak** [comment]
FYI: Firefox is the same, error is (something like) this:
```
The certificate is only valid for yelm.tdev.ly.
(error code: ssl_error_bad_cert_domain)
```

**Comment by gwicksted** [comment]
This is crucial for language adoption (especially with beginners).  Once fixed, place a copy of the link in the readme.md too.  And at least one screenshot of the app showing example code.

**Comment by sagevann** [comment]
Graeme Wicksted,

You should probably create a separate issue for your documentation
requests. Fixing the SSL cert doesn't require anything be done with the
links and screenshots.

Sage

**Comment by gwicksted** [comment]
@sagevann Sorry for hijacking like that!  It was not my intention.  I have adjusted my comment to reflect my impression of the issue and why I feel this ticket is important ... instead of suggesting a completely unrelated course of action!  I hope for the sake of this project it can be resolved quickly.

**Comment by mmoskal** [comment]
The SSL cert is fixed (for a few days now). Thanks!

We'll take off the password once we're ready for more main-stream use.
