### ISSUE TITLE
Undo: Does not work 100% of the time

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/kindscript#4]
Undo failed to remove added block. Sometimes it works but not consistently.
a. Add 2 Blocks (Clear screen and Show String)
b. Move the above blocks together
c. Add a 3rd block (Show Number) and drop right under shows string
d. Click Undo x 2 and the Show number goes away
e. Add 3rd block again (Show String and drop under 2nd block)
f. Click Undo (as many times as you want)
The block may not be removed ****** 30-50% of the time the block is removed*******

**Comment by pelikhan** [comment]
Now using built in undo feature in blockly
